# Generated by Django 4.2.5 on 2023-10-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_hoursdelta_tour_alter_payment_network_tourdelta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=100, verbose_name='Сумма'),
        ),
    ]
