# Generated by Django 4.2.5 on 2023-10-21 07:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено в: ')),
                ('network', models.CharField(choices=[('BTC', 'Btc'), ('MONERO', 'Monero'), ('TON', 'Ton'), ('TRON', 'Tron')], max_length=10)),
                ('currency', models.CharField(choices=[('BTC', 'Btc'), ('MONERO', 'Monero'), ('TON', 'Ton'), ('TRON', 'Tron')], max_length=10)),
                ('order_id', models.IntegerField(verbose_name='ID заказа')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('url_callback', models.CharField(max_length=200, verbose_name='Ссылка')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tourdelta',
            name='hours_delta',
        ),
        migrations.RemoveField(
            model_name='tourdelta',
            name='tour',
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('USD', 'Usd'), ('RUB', 'Rub'), ('BYN', 'Byn'), ('UAH', 'Uah'), ('KZT', 'Kzt')], max_length=10),
        ),
        migrations.DeleteModel(
            name='HoursDelta',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
        migrations.DeleteModel(
            name='TourDelta',
        ),
    ]
