# Generated by Django 4.2.5 on 2023-10-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_wallet_remove_tourdelta_hours_delta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='id',
            new_name='uuid',
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('USD', 'Usd'), ('RUB', 'Rub'), ('BYN', 'Byn'), ('UAH', 'Uah'), ('KZT', 'Kzt'), ('BTC', 'Btc'), ('XMR', 'Xmr'), ('TON', 'Ton'), ('USDT', 'Usdt')], max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='network',
            field=models.CharField(choices=[('BTC', 'Btc'), ('XMR', 'Xmr'), ('TON', 'Ton'), ('TRON', 'Tron')], max_length=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('BTC', 'Btc'), ('XMR', 'Xmr'), ('TON', 'Ton'), ('USDT', 'Usdt')], max_length=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='network',
            field=models.CharField(choices=[('BTC', 'Btc'), ('XMR', 'Xmr'), ('TON', 'Ton'), ('TRON', 'Tron')], max_length=10),
        ),
    ]
