# Generated by Django 4.2.5 on 2023-10-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_rename_id_payment_uuid_rename_id_wallet_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=15, max_digits=100, verbose_name='Сумма'),
        ),
    ]
