# Generated by Django 4.2.5 on 2023-11-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_wallet_balance_wallet_mnemonics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
