# Generated by Django 4.2.5 on 2023-11-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_alter_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='priv_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
