# Generated by Django 4.2.5 on 2023-12-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_wallet_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_commission', models.PositiveIntegerField(default=2)),
            ],
        ),
    ]
